<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentFTP" Version="51.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GeoFun.GNSS.Net\GeoFun.GNSS.Net.csproj" />
    <ProjectReference Include="..\GeoFun\GeoFun.csproj" />
  </ItemGroup>

</Project>